version: '3'
services:
  app:
    container_name: backend_pucetec_api
    restart: on-failure
    ports:
      - 9108:9108
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
